### ISSUE TITLE
Error gramatical

### ISSUE THREAD

**Issue by hugoocoto** [AsierCL/Arch-Instalation-Guide#1]
Hay una confusion en el apartado donde  se necesita modificar un archivo, se confundio el comando "vim" para abrir el editor con "nano". Muchas gracias.

**Comment by AsierCL** [comment]
La guía está pensada para usuarios novatos de Linux, con poca experiencia en terminal. Uso nano para no tener que dedicar un apartado entero a como salir de vim. Gracias por el feedback.
